[session.defaults]
# These are the default settings for all sessions, but can be overridden on a per-session basis below

# NOTES:
# Times are in seconds. I.E - a 10 minute talk is 10 mins * 60 sec/min = 600 sec
# Date strings should be in ISO format, I.E 1 PM on November 19th in AZ time is
# November 19 2021 13:00:00 GMT-0700

test_value = 10
talk_length = 600 # 600 seconds/10 minutes

[session.A]

number_talks = 5
start_time = "November 19 2021 13:00:00 GMT-0700"
talk_length = 600
name = "A"

[session.B]

start_time = ""
